### ISSUE TITLE
This show makes no sense

### ISSUE THREAD

**Issue by thieman** [Patchus/theofficepicker#1]
I don't understand what the parallel plotline in Scranton is for at all. Maybe they are setting up for a spin-off where Coach Kilmer goes into the corporate world or something but it's not very well-established. Plus I guess they like to play basketball in this office and if this show pulls a sport bait-and-switch on me I'm going to be disappointed. I came here to watch football and Jon Voight cussin' at people in a bad Texas accent.

Maybe you're not responsible for this as a random programmer on the Internet but if you could somehow get a message to the writers letting them know the two plotlines thing isn't working that'd be great.

**Comment by eriktaubeneck** [comment]
+1

**Comment by Patchus** [comment]
This should be resolved. It was an issue with our season 5 number.
